apiVersion: v1
kind: Pod
metadata:
  labels:
    key: value2
  name: watcher
spec:
  containers:
    - name: webserver
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: webwatcher
      image: afakharany/watcher:latest